let promiseTest = new Promise((resolve, reject) => {
    let a = 1 + 2

    if (a == 4) {
        resolve('Satisfied the condition ðŸ˜Š')
    } else {
        reject('failed to satisfied the condition ðŸ˜’')
    }
})

promiseTest.then((msg) => {
    console.log(msg)
}).catch((err) => {
    console.log(err)
})

